### ISSUE TITLE
Does not work with nusys demos.

### ISSUE THREAD

**Issue by trhodeos** [trhodeos/spicy#1]
For whatever reason, nothing boots. Need to investigate a bit more.

**Comment by deadcast2** [comment]
Huh, I tried compiling and running the nu0 demo and it performed fine. Maybe you fixed this issue already? :)

**Comment by trhodeos** [comment]
Yeah, I think this issue is a bit old.. However, last I remember, I couldn't get all of the nusys demos working, only the first couple.

**Comment by AlejandroGuardado** [comment]
Hello:
I'm new to N64 development (and low level programming for that matter).
I've been trying to compile the samples from nusys with no success. Everything _seems_ to be going OK (codesegment.o file is generated), until spicy is run.

```
C:/N64/N64_TOOLCHAIN/bin/spicy C:/N64/N64_SDK/nintendo/n64kit/nusys/sample/nu5/spec -IC:/N64/N64_SDK/nintendo/n64kit/nusys/include -r nu5.n64 -e nu5.out
panic: unexpected error runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
main.main()
        /Users/trhodes/go/src/github.com/trhodeos/spicy/cmd/spicy/main.go:106 +0x8b2
make: *** [Makefile:51: nu5.n64] Error 2
```

[These are my files](https://drive.google.com/file/d/1FehQidtBmt1foqOj4snOX7ZrRCqU6SRI/view?usp=sharing)
- Shell script
- Modified Makefile for nu0
- Modified PRdefs

I'm using Windows 10. spicy is inside N64_TOOLCHAIN folder with all n64chain exes.

**Comment by deadcast2** [comment]
Hello!

What's your spec file look like?

**Comment by AlejandroGuardado** [comment]
> 
> 
> Hello!
> 
> What's your spec file look like?

Mostly the same as they are on the sample folders. I only changed the "codesegment" line:

```
#include <nusys.h>

/* Use all graphic microcodes */
beginseg
	name	"code"
	flags	BOOT OBJECT
	entry 	nuBoot
	address NU_SPEC_BOOT_ADDR
        stack   NU_SPEC_BOOT_STACK
	include "$(CURRENTDIR)/codesegment.o"
	include "$(ROOT)/usr/lib/PR/rspboot.o"
	include "$(ROOT)/usr/lib/PR/gspF3DEX2.fifo.o"
	include "$(ROOT)/usr/lib/PR/gspL3DEX2.fifo.o"
	include "$(ROOT)/usr/lib/PR/gspF3DEX2.Rej.fifo.o"
        include "$(ROOT)/usr/lib/PR/gspF3DEX2.NoN.fifo.o"
        include "$(ROOT)/usr/lib/PR/gspF3DLX2.Rej.fifo.o"
	include "$(ROOT)/usr/lib/PR/gspS2DEX2.fifo.o"
endseg

beginwave
	name	"nu0"
	include	"code"
endwave
```

**Comment by deadcast2** [comment]
Thanks, the spec looks fine to me. Could you try running spicy with the "-d" verbose option? Might give us some more clarification to where the problem is occurring.

**Comment by AlejandroGuardado** [comment]
```
C:/N64/N64_TOOLCHAIN/bin/spicy -d C:/N64/N64_SDK/nintendo/n64kit/nusys/sample/nu0/spec -IC:/N64/N64_SDK/nintendo/n64kit/nusys/include -r nu0.n64 -e nu0.out
time="2021-01-11T19:13:33-07:00" level=info msg="About to run mips64-elf-gcc -P -E -U_LANGUAGE_C -D_LANGUAGE_MAKEROM - -IC:/N64/N64_SDK/nintendo/n64kit/nusys/include\n"
time="2021-01-11T19:13:33-07:00" level=debug msg="stdout: "
time="2021-01-11T19:13:33-07:00" level=info msg="Parsing spec"
panic: unexpected error runtime error: invalid memory address or nil pointer dereference

goroutine 1 [running]:
main.main()
        /Users/trhodes/go/src/github.com/trhodeos/spicy/cmd/spicy/main.go:106 +0x8b2

```

**Comment by deadcast2** [comment]
Can you provide your spec and nu5.out files? I'd like to try myself using the prebuilt toolchain I'm using in UltraEd. Thanks

**Comment by nterry** [comment]
@trhodeos  Im seeing the same thing. Here is my output:

```
spicy spec -d --as_command=mips-n64-as --cpp_command=mips-n64-gcc --ld_command=mips-n64-ld --objcopy_command=mips-n64-objcopy -I/usr/include/n64/nusys -s 32 -r 3rdPersonDemo.n64 -e 3rdPersonDemo.out
INFO[0000] About to run mips-n64-gcc -P -E -U_LANGUAGE_C -D_LANGUAGE_MAKEROM - -I/usr/include/n64/nusys

DEBU[0000] stdout: beginseg
 name "code"
 flags BOOT OBJECT
 entry nuBoot
 address 0x80025c00
    stack nuMainStack + 0x2000
 include "codesegment.o"
 include "/usr/lib/n64/PR/rspboot.o"
 include "/usr/lib/n64/PR/gspF3DEX2.fifo.o"
 include "/usr/lib/n64/PR/gspL3DEX2.fifo.o"
 include "/usr/lib/n64/PR/gspF3DEX2.Rej.fifo.o"
    include "/usr/lib/n64/PR/aspMain.o"
    include "/usr/lib/n64/PR/n_aspMain.o"
    include "/usr/lib/n64/PR/gspF3DEX2.NoN.fifo.o"
    include "/usr/lib/n64/PR/gspF3DLX2.Rej.fifo.o"
 include "/usr/lib/n64/PR/gspS2DEX2.fifo.o"
endseg
beginseg
 name "pbank"
 flags RAW
 include "src/audio/bank_sfx.ptr"
endseg
beginseg
 name "wbank"
 flags RAW
 include "src/audio/bank_sfx.wbk"
endseg
beginseg
 name "sfx"
 flags RAW
 include "src/audio/bank_sfx.bfx"
endseg
beginwave
 name "3rdpersondemo"
 include "code"
 include "bank_sfx_pbank"
 include "bank_sfx_wbank"
 include "bank_sfx_sfx"
endwave

INFO[0000] Parsing spec
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xa0 pc=0x532217]

goroutine 1 [running]:
github.com/trhodeos/spicy.convertWaveAst(0xc420103300, 0xc4200e5b38, 0xc420012c05, 0x3, 0xc4200e5c08)
        /Users/trhodes/go/src/github.com/trhodeos/spicy/spec.go:205 +0x137
github.com/trhodeos/spicy.convertAstToSpec(0xc420102b80, 0x4, 0x4, 0xc42000c0c0, 0x1, 0x1, 0x0, 0xc420045cc8, 0xc420045cc8)
        /Users/trhodes/go/src/github.com/trhodeos/spicy/spec.go:237 +0x1e1
github.com/trhodeos/spicy.ParseSpec(0x5b3ca0, 0xc4200be0e0, 0x5b40c0, 0xc42004e580, 0xc42004e570)
        /Users/trhodes/go/src/github.com/trhodeos/spicy/spec.go:279 +0x124
main.main()
        /Users/trhodes/go/src/github.com/trhodeos/spicy/cmd/spicy/main.go:104 +0x314
make: *** [Makefile:88: 3rdPersonDemo.n64] Error 2
```

I took a look here: https://github.com/trhodeos/spicy/blob/47409fb73e0b20b323c46cc06a3858d0a252a817/spec.go#L205 but nothing jumped out at me. I'm not an expert go developer however...

EDIT:

Upon further inspection, the lone hyphen in the command ''mips-n64-gcc -P -E -U_LANGUAGE_C -D_LANGUAGE_MAKEROM - -I/usr/include/n64/nusys" just before the -I seems suspicious... that hyphen like that is for stdin i believe... 

EDIT EDIT:

If I comment out the wave section in the spec, I get the following:

`spicy -d --as_command=mips-n64-as --cpp_command=mips-n64-gcc --ld_command=mips-n64-ld --objcopy_command=mips-n64-objcopy -I/usr/include/n64/nusys -s 32 -r 3rdPersonDemo.n64 -e 3rdPersonDemo.out spec
INFO[0000] About to run mips-n64-gcc -P -E -U_LANGUAGE_C -D_LANGUAGE_MAKEROM - -I/usr/include/n64/nusys

> DEBU[0000] stdout: beginseg
>  name "code"
>  flags BOOT OBJECT
>  entry nuBoot
>  address 0x80025c00
>     stack nuMainStack + 0x2000
>  include "codesegment.o"
>  include "/usr/lib/n64/PR/rspboot.o"
>  include "/usr/lib/n64/PR/gspF3DEX2.fifo.o"
>  include "/usr/lib/n64/PR/gspL3DEX2.fifo.o"
>  include "/usr/lib/n64/PR/gspF3DEX2.Rej.fifo.o"
>     include "/usr/lib/n64/PR/aspMain.o"
>     include "/usr/lib/n64/PR/n_aspMain.o"
>     include "/usr/lib/n64/PR/gspF3DEX2.NoN.fifo.o"
>     include "/usr/lib/n64/PR/gspF3DLX2.Rej.fifo.o"
>  include "/usr/lib/n64/PR/gspS2DEX2.fifo.o"
> endseg
> beginseg
>  name "pbank"
>  flags RAW
>  include "src/audio/bank_sfx.ptr"
> endseg
> beginseg
>  name "wbank"
>  flags RAW
>  include "src/audio/bank_sfx.wbk"
> endseg
> beginseg
>  name "sfx"
>  flags RAW
>  include "src/audio/bank_sfx.bfx"
> endseg
> 
> INFO[0000] Parsing spec
> DEBU[0000] Parsed: &{[]}
> makemask 3rdPersonDemo.n64
> Masking 3rdPersonDemo.n64.
> Generate checksum: 0xF8CA4DDC303A4DDC`

The parsed output appears to be empty...

When I run the built rom, it physically executed without crashing, but nothing happens. I suspect the jump to 0x400 (ish) happens, but there are no more instructions to execute, because the rom is not assembled correctly...

But I am not sure...

**Comment by nterry** [comment]
Ok, instead of editing my comment again, I think Ive found one of the issues...

Turns out, you dont check for null here: https://github.com/trhodeos/spicy/blob/47409fb73e0b20b323c46cc06a3858d0a252a817/spec.go#L205

So if the 'included' segment by the given name on the current statement on the current wave doesnt exist, the code proceeds and throws an exception

For example, heres my spec:

> #include "include/main.h"
> #include <nusys.h>
> 
> 
> beginseg
> 	name	"code"
> 	flags	BOOT OBJECT
> 	entry 	nuBoot
> 	address NU_SPEC_BOOT_ADDR
>     stack   NU_SPEC_BOOT_STACK
> 	include "codesegment.o"
> 	include "/usr/lib/n64/PR/rspboot.o"
> 	include "/usr/lib/n64/PR/gspF3DEX2.fifo.o"
> 	include "/usr/lib/n64/PR/gspL3DEX2.fifo.o"
> 	include "/usr/lib/n64/PR/gspF3DEX2.Rej.fifo.o"
>     include "/usr/lib/n64/PR/aspMain.o"
>     include "/usr/lib/n64/PR/n_aspMain.o"
>     include "/usr/lib/n64/PR/gspF3DEX2.NoN.fifo.o"
>     include "/usr/lib/n64/PR/gspF3DLX2.Rej.fifo.o"
> 	include "/usr/lib/n64/PR/gspS2DEX2.fifo.o"
> endseg
> 
> beginseg
> 	name "pbank"
> 	flags RAW
> 	include "src/audio/bank_sfx.ptr"
> endseg
> 
> beginseg
> 	name "wbank"
> 	flags RAW
> 	include "src/audio/bank_sfx.wbk"
> endseg
> 
> beginseg
> 	name "sfx"
> 	flags RAW
> 	include "src/audio/bank_sfx.bfx"
> endseg
> 
> 
> beginwave
> 	name	"3rdpersondemo"
> 	include	"code"
> 
> 	include "bank_sfx_pbank"
> 	include "bank_sfx_wbank"
> 	include "bank_sfx_sfx"
> endwave
> 
> /*
> beginseg
> 	name	"gfx_dl_buf"
> 	after	"code"
> 	flags	OBJECT
> 	include	"src/gfx_dl_buf.o"
> endseg
> 
> beginwave
> 	name	"nulod"
> 	include	"code"
> 	include "gfx_dl_buf"
> endwave
> */

In the wave, the 'bank_sfx_pbank' segment doesnt exist (the 'pbank' one does). So if i change it to 'pbank' (and all the other ones as well), i get a successful build.

However, the ROM still hangs...
